### ISSUE TITLE
Cannot assume `jq` is installed on runners named `GitHub Actions` 

### ISSUE THREAD

**Issue by IanButterworth** [julia-actions/cache#104]
Posted by @musoke here https://github.com/julia-actions/cache/pull/88#issuecomment-1892663926

----

FYI: this change seems to have broken one of my CI runs. I think the problem is that I'm running in a container on a GitHub hosted runner, so jq isn't installed.
v1.4.1 works but v1.5.1 does not.

here's a log: https://github.com/musoke/WolframExpr.jl/actions/runs/7532058237/job/20501935392#step:5:65

**Comment by musoke** [comment]
Does that `jq` install action work inside containers?

Why does check for a GitHub hosted runner exist? Presumably this is because those runners already have `jq` installed.  Is there a problem with trying to install `jq` anyway?  It looks like it is set not to force installation if it is already installed.  Perhaps those checks are brittle too?

**Comment by musoke** [comment]
I'm happy submit a PR if there is a clear solution.
