### ISSUE TITLE
Why are we using this specific commit of `actions/cache`?

### ISSUE THREAD

**Issue by DilumAluthge** [julia-actions/cache#119]
The [`action.yml`](https://github.com/julia-actions/cache/blob/main/action.yml) file in this repo currently pins `actions/cache` to the following commit:

https://github.com/julia-actions/cache/blob/0413f3b1aed10bc4d367678d38a695e81c7c09f5/action.yml#L118-L118

Now, it is very good that we are pinning all external actions to the full-length commit hash.

However, what is unusual here is that specific commit we pin to doesn't seem to correspond to any tag or branch; if you go to https://github.com/actions/cache/commit/4d4ae6ae148a43d0fd1eda1800170683e9882738 you see the following message:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

This isn't necessarily a problem, but it seems a bit unusual. @IanButterworth Would you happen to know why we are using this specific commit of `actions/cache`?

IIUC, this was introduced in https://github.com/julia-actions/cache/pull/71.

cc: @IanButterworth @omus @SaschaMann @rikhuijzer

**Comment by IanButterworth** [comment]
Sorry, that snuck in to #71 
It's from this branch on my fork https://github.com/actions/cache/compare/main...IanButterworth:cache-1:ib/update

Having git commits rather than tags is clearly the right thing, but it makes catching this kind of error in code review harder.

I propose we update `actions/cache` to the v4.0.2 commit https://github.com/actions/cache/releases/tag/v4.0.2

https://github.com/julia-actions/cache/pull/120

**Comment by IanButterworth** [comment]
Actually v3.3.3 makes more sense (https://github.com/julia-actions/cache/pull/121) as Dilum points out, v4.0.0 was breaking because it updates to node20, so better to fix this before a breaking change is needed
